here is the data set taken from a bank which collected some information from the bank , and a deciding factor that custumer has left the bank or not
@ bank observed that their custumers aur leaving the bank  so we have to se the corelation that weather the custumer will stay in bank aur not  
@ this is to prevent the custumers to leave the bank by giving that custumer offer

# IMPORTING THE LIBRARIES


In [11]:
import numpy as np
import pandas as pd 
import tensorflow as tf

In [12]:
tf.__version__

'2.10.0'

# data pre processing

In [13]:
dataset =pd.read_csv(r"C:\Users\RIYAN SINGH\Desktop\course\Machine Learning A-Z (Codes and Datasets)\Part 8 - Deep Learning\Section 39 - Artificial Neural Networks (ANN)\Python\Churn_Modelling.csv")
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values# here we are having key values( which ARE NOT USEFUL) of the custumer in first 3 columns so we exclude them for ann easie

In [14]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [15]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

# ENCODING THE CATAGORICAL DATA 

here we are using the lable encoder for encoding the male and female 

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [17]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

# appling one hut coding to the geographical column

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])],remainder='passthrough' )
x = np.array(ct.fit_transform(x))

In [19]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

# spliting the data into test and train set

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=1)

# featur escaling 
feature scaling is so important to the deep learning that we feature scale whole data


In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)
print(x_train)

[[-0.99850112  1.71490137 -0.57273139 ... -1.55337352  0.97725852
   0.42739449]
 [ 1.00150113 -0.58312392 -0.57273139 ... -1.55337352 -1.02327069
  -1.02548708]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
  -0.94479772]
 ...
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
  -0.14096853]
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
   0.01781218]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017 -1.02327069
  -1.15822478]]


# BUILDING THE ANN

INITIALLING THE ANN

In [22]:
ann= tf.keras.models.Sequential()

add 1st hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding the 2nd hidden layes.
here we can change the hyper parameter to make output more accurate

In [24]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

add the output layer ,in output layer you have the output neurons as per the output class
as we only have binary class so we have 1 neuron here 

In [25]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))# when the class increases then we use softmax activation function

# training the ann


we have to give 3 parameters while training the ann ( OPTIMIZER, LOSS_FUNCTION,MATRIX)


In [26]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


TRAINING THE DATASET ON TRAINING DATA

In [37]:
ann.fit(x_train,y_train,batch_size=32,epochs=50)

Epoch 1/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3314 - accuracy: 0.8634
Epoch 2/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8634
Epoch 3/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3315 - accuracy: 0.8633
Epoch 4/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3315 - accuracy: 0.8618
Epoch 5/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 0.8633
Epoch 6/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8641
Epoch 7/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8631
Epoch 8/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8645
Epoch 9/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3311 - accuracy: 0.8634
Epoch 10/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8627

# pridecting the single value 

here input of predicted value must b in 2d array

same scaling must b there ,so to make it of same scale we have used transform method from standard scaler

In [39]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 22ms/step
[[False]]


# PREDICTING THE TEST SET

In [40]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 791us/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


# CONFUSSION MATRIX

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1526   59]
 [ 208  207]]


0.8665